[
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/mine.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/mine.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/mine.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp"
]


[
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/mine.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/mine.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/mine.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp",
    "http://localhost:5173/src/assets/mines/images/star.webp"
]

 [null, null, null, null, null, null, null, null, null, null,
     null, 'http://localhost:5173/src/assets/mines/images/star.webp',
      null, null, null, null, null, 'http://localhost:5173/src/assets/mines/images/star.webp',
       'http://localhost:5173/src/assets/mines/images/star.webp', null, null, null, null,
        null, null]